name: Deploy static website to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Sync website files to S3
        run: |
          aws s3 sync ./website s3://my-static-site-bucket-dawdawdawdawd --delete

      - name: Apply Terraform changes
        run: |
          terraform init
          terraform apply -auto-approve
