name: Deploy static website to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::424499126527:role/github-actions-s3-role
          aws-region: eu-central-1

      - name: Sync website files to S3
        run: |
          aws s3 sync ./website s3://my-static-site-bucket-dawdawdawdawd --delete

